=== veryyoung/p2p-renting/hybrid/p2p_renting/platforms/ios/www/js/jxhl.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="jxhl" targetNamespace="http://halo-studio.com/jxhl" elementFormDefault="qualified" xmlns="http://halo-studio.com/jxhl" xmlns:mstns="http://halo-studio.com/jxhl" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="jxhl-base" mixed="true">
        <xs:attribute name="local_var" type="jxhl-local-var"></xs:attribute>
        <xs:anyAttribute></xs:anyAttribute>
    </xs:complexType>
    <xs:complexType name="jxhl-htmltagbase">
        <xs:complexContent>
            <xs:extension base="jxhl-base">
                <xs:choice>
                    <xs:group ref="group-htmltag" maxOccurs="unbounded">
                    </xs:group>
                </xs:choice>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:simpleType name="jxhl-dock">
        <xs:restriction base="xs:string">
            <xs:enumeration value="top" />
            <xs:enumeration value="left" />
            <xs:enumeration value="right" />
            <xs:enumeration value="bottom" />
            <xs:enumeration value="center" />
            <xs:enumeration value="fill" />
            <xs:enumeration value="fix" />
            <xs:enumeration value="float" />
            <xs:enumeration value="auto" />
            <xs:enumeration value="none" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="jxhl-visible">
        <xs:restriction base="xs:string">
            <xs:enumeration value="0" />
            <xs:enumeration value="1" />
            <xs:enumeration value="false" />
            <xs:enumeration value="true" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="jxhl-local-var">
        <xs:restriction base="xs:string">
            <xs:pattern value="[^=]?[0-9a-zA-Z_$]*" />
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="jxhl-control" mixed="false">
        <xs:complexContent>
            <xs:extension base="jxhl-base">
                <xs:sequence>
                    <xs:choice>
                        <xs:group ref="group-element" maxOccurs="unbounded"/>
                    </xs:choice>
                </xs:sequence>
                <xs:attributeGroup ref="group-attribute">
                </xs:attributeGroup>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="jxhl-html">
        <xs:complexContent mixed="false">
            <xs:extension base="jxhl-base">
                <xs:group ref="group-htmltag" maxOccurs="unbounded">
                </xs:group>
                <xs:attributeGroup ref="group-attribute">
                </xs:attributeGroup>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="jxhl-image">
        <xs:complexContent mixed="false">
            <xs:extension base="jxhl-base">
                <xs:attributeGroup ref="group-attribute">
                </xs:attributeGroup>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="jxhl-frame">
        <xs:complexContent mixed="true">
            <xs:extension base="jxhl-base">
                <xs:attributeGroup ref="group-attribute">
                </xs:attributeGroup>
                <xs:attribute name="frame_scrolling">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value=""></xs:enumeration>
                            <xs:enumeration value="auto"></xs:enumeration>
                            <xs:enumeration value="yes"></xs:enumeration>
                            <xs:enumeration value="no"></xs:enumeration>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
                <xs:attribute name="src" type="xs:string"></xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="jxhl-label">
        <xs:complexContent mixed="true">
            <xs:extension base="jxhl-base">
                <xs:attributeGroup ref="group-attribute">
                </xs:attributeGroup>
                <xs:attribute name="src" type="xs:string"></xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:group name="group-element">
        <xs:choice>
            <xs:element name="html" type="jxhl-html" />
            <xs:element name="image" type="jxhl-image" />
            <xs:element name="label" type="jxhl-label"></xs:element>
            <xs:element name="frame" type="jxhl-frame" />
            <xs:element name="panel" type="jxhl-control" />
        </xs:choice>
    </xs:group>
    <xs:group name="group-htmltag">
        <xs:choice>
            <xs:element name="div">
                <xs:complexType>
                    <xs:anyAttribute/>

                </xs:complexType>
            </xs:element>
            <xs:element name="table" type="jxhl-htmltagbase">
                <xs:complexType>
                    <xs:anyAttribute/>
                </xs:complexType>
            </xs:element>
            <xs:element name="span" type="jxhl-htmltagbase">
                <xs:complexType>
                    <xs:anyAttribute/>
                </xs:complexType>
            </xs:element>
            <xs:element name="tr" type="jxhl-htmltagbase">
                <xs:complexType>
                    <xs:anyAttribute/>
                </xs:complexType>
            </xs:element>
            <xs:element name="td" type="jxhl-htmltagbase">
                <xs:complexType>
                    <xs:anyAttribute/>
                </xs:complexType>
            </xs:element>
            <xs:element name="label" type="jxhl-htmltagbase">
                <xs:complexType>
                    <xs:anyAttribute/>
                </xs:complexType>
            </xs:element>
            <xs:element name="nav" type="jxhl-htmltagbase">
                <xs:complexType>
                    <xs:anyAttribute/>
                </xs:complexType>
            </xs:element>
            <xs:element name="audio" type="jxhl-htmltagbase">
                <xs:complexType>
                    <xs:anyAttribute/>
                </xs:complexType>
            </xs:element>
            <xs:element name="video" type="jxhl-htmltagbase" />
            <xs:element name="iframe" type="jxhl-htmltagbase" />
            <xs:element name="a" type="jxhl-htmltagbase" />
            <xs:element name="strong" type="jxhl-htmltagbase" />
            <xs:element name="ul" type="jxhl-htmltagbase" />
            <xs:element name="ol" type="jxhl-htmltagbase" />
            <xs:element name="li" type="jxhl-htmltagbase" />
            <xs:element name="meta" type="jxhl-htmltagbase" />
            <xs:element name="link" type="jxhl-htmltagbase" />
            <xs:element name="script" type="jxhl-htmltagbase" />
            <xs:element name="title" type="jxhl-htmltagbase" />
            <xs:element name="code" type="jxhl-htmltagbase" />
            <xs:element name="pre" type="jxhl-htmltagbase" />
            <xs:element name="dl" type="jxhl-htmltagbase" />
            <xs:element name="dd" type="jxhl-htmltagbase" />
            <xs:element name="dt" type="jxhl-htmltagbase" />
            <xs:element name="input" type="jxhl-htmltagbase" />
            <xs:element name="select" type="jxhl-htmltagbase" />
            <xs:element name="footer" type="jxhl-htmltagbase" />
            <xs:element name="br" type="jxhl-htmltagbase" />
        </xs:choice>
    </xs:group>
    <xs:attributeGroup name="group-attribute">
        <xs:attribute name="id" type="xs:string"></xs:attribute>
        <xs:attribute name="dock" type="jxhl-dock" use="required"></xs:attribute>
        <xs:attribute name="width" type="xs:int"></xs:attribute>
        <xs:attribute name="height" type="xs:int"></xs:attribute>
        <xs:attribute name="left" type="xs:int"></xs:attribute>
        <xs:attribute name="top" type="xs:int"></xs:attribute>
        <xs:attribute name="css_name" type="xs:string"></xs:attribute>
        <xs:attribute name="css_text" type="xs:string"></xs:attribute>
        <xs:attribute name="visible" type="jxhl-visible"></xs:attribute>
        <xs:attribute name="border_width" type="xs:string"></xs:attribute>
        <xs:attribute name="margin" type="xs:string"></xs:attribute>
        <xs:attribute name="opacity" type="xs:decimal"></xs:attribute>
    </xs:attributeGroup>
    
    <xs:element name="jxhl">
        <xs:complexType mixed="true">
            <xs:choice maxOccurs="unbounded">
                <xs:group ref="group-element" />
                <xs:element name="runnable" type="xs:string"></xs:element>
            </xs:choice>
        </xs:complexType>
        
        <!--<xs:element name="panel"></xs:element>
        <xs:element name="label"></xs:element>
        <xs:element name="html"></xs:element>
        <xs:element name="frame"></xs:element>
        <xs:element name="image"></xs:element>-->
    </xs:element>
    
</xs:schema>

=== veryyoung/p2p-renting/hybrid/p2p_renting/www/layout/landlord/wait.xml
<?xml version="1.0" encoding="utf-8"?>
<jxhl xmlns="http://halo-studio.com/jxhl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://halo-studio.com/jxhl ../../js/jxhl.xsd">
    <panel dock="top" height="70" template="../common/head.xml" template_args="header">
        
    </panel>
    <html dock="fill" css_name="app-scroll">
        <div class="container">
            <div class="form">
                <div class="form-group">
                    <button local_var="btn_publish" type="button" class="btn btn-brightgreen">发布房源</button>
                </div>
                <div class="form-group">
                    <button local_var="btn_suggest" type="button" class="btn btn-red">查看推荐</button>
                </div>
            </div>
        </div>
    </html>
    <runnable>
        <![CDATA[
            var header = {'title':'有房出租','useBack':false,'backCall':function(){},
            'useMore':true, 'moreCss':'fa-user', 'moreCall':function(){
                jxhl.utility.loadJxhlLayout('renter/wait');
            }};
            require(['pages/landlord-wait'], function(a){
                a.init(jxhl$container, jxhl$arguments, jxhl$localVars);
            });
        ]]>
    </runnable>
</jxhl>

=== veryyoung/p2p-renting/hybrid/p2p_renting/www/layout/signin.xml
<?xml version="1.0" encoding="utf-8"?>
<jxhl xmlns="http://halo-studio.com/jxhl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://halo-studio.com/jxhl ../js/jxhl.xsd">
    <panel dock="bottom" height="51" border_width="1,0,0,0" css_name="text-center" css_text="border-top:1px solid #e8e9e9; background:#f8f9f9; line-height:50px; overflow:hidden;">
        <html dock="fill">
           
        </html>
    </panel>
    <html dock="fill" css_name="app-scroll">
        <div class="container">
            <div class="form">
                <div class="form-group">
                    <h2>登录</h2>
                </div>
                <div class="form-group">
                    <input local_var="txt_mobile" type="text" class="form-control" placeholder="手机"/>
                </div>
                <div class="form-group">
                    <input local_var="txt_pwd" type="password" class="form-control" placeholder="密码"/>
                </div>
                <div class="form-group">
                    <button local_var="btn_signin" type="button" class="btn btn-primary">登录</button>
                </div>
                <div class="form-group text-center" local-id="div-msg"></div>
            </div>
        </div>
    </html>
    <runnable>
        <![CDATA[
            
        ]]>
    </runnable>
</jxhl>

=== veryyoung/p2p-renting/hybrid/p2p_renting/platforms/ios/www/layout/chat.xml
<?xml version="1.0" encoding="utf-8"?>
<jxhl xmlns="http://halo-studio.com/jxhl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://halo-studio.com/jxhl ../js/jxhl.xsd">
    <panel dock="top" height="70" template="common/head.xml" template_args="header">
        
    </panel>
    <panel dock="bottom" height="40" css_text="background:#efefef;">
        <html dock="left" width="0.75*" css_text="padding:0px 5px 0px 8px;">
            <input local_var="txt_key" class="form-control" placeholder="请输入消息.."/>
        </html>
        <html dock="fill" css_text="padding:0px 3px;">
            <button local_var="btn_sendmsg" type="button" class="btn btn-brightgreen">发送</button>
        </html>
    </panel>
    <html dock="fill" css_name="app-scroll">
        <div class="container">
            <div local_var="div_status">聊天状态..</div>
            <div local_var="div_result">
               
            </div>
        </div>
    </html>
    <runnable>
        <![CDATA[
            var header = {'title':'高效沟通中..','useBack':true,'backCall':function(){
                jxhl.historyBack();   
            }};
            require(['pages/chat'], function(a){
                a.init(jxhl$container, jxhl$arguments, jxhl$localVars);
            });
        ]]>
    </runnable>
</jxhl>

=== veryyoung/p2p-renting/hybrid/p2p_renting/platforms/android/assets/www/layout/signin.xml
<?xml version="1.0" encoding="utf-8"?>
<jxhl xmlns="http://halo-studio.com/jxhl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://halo-studio.com/jxhl ../js/jxhl.xsd">
    <html dock="fill" css_name="app-scroll">
        <div class="container">
            <div class="form">
                <div class="form-group">
                    <h2>登录</h2>
                </div>
                <div class="form-group">
                    <input local_var="txt_mobile" type="text" class="form-control" placeholder="手机或用户名"/>
                </div>
                <div class="form-group">
                    <input local_var="txt_pwd" type="password" class="form-control" placeholder="密码"/>
                </div>
                <div class="form-group">
                    <button local_var="btn_signin" type="button" class="btn btn-primary">登录</button>
                </div>
                <div class="form-group">
                    <button local_var="btn_signup" type="button" class="btn btn-brightgreen">还没有账号</button>
                </div>
                <div class="form-group text-center" local-id="div-msg"></div>
            </div>
        </div>
    </html>
    <runnable>
        <![CDATA[
            require(['pages/signin'], function(a){
                a.init(jxhl$container, jxhl$arguments, jxhl$localVars);
            });
        ]]>
    </runnable>
</jxhl>

=== veryyoung/p2p-renting/hybrid/p2p_renting/www/layout/common/head.xml
<?xml version="1.0" encoding="utf-8"?>
<jxhl xmlns="http://halo-studio.com/jxhl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://halo-studio.com/jxhl ../../js/jxhl.xsd">
    
    <panel dock="fill" border_width="0,0,1,0" css_name="ui-head text-center">
    <panel dock="top" height="20"></panel>
    
    <html dock="fill">
        <div class="container">
            <div class="row">
                <div style="margin:0px 10px;">
                    <i local_var="i_return" local-id="page-head-left" class="pull-left fa fa-1x5 fa-reply" style="margin-top:18px; margin-right:5px; display:none;"> </i>
                    <span local_var="label_title"> </span>
                    <i local_var="i_right" local-id="page-head-right" class="pull-right fa" style="display:none; margin-top:18px;"> </i>
                </div>
            </div>
        </div>
    </html>
    </panel>
    <runnable>
        <![CDATA[
        var config = jxhl$arguments;
        if(!config) return;
        label_title.innerHTML = config.title||'';
        if(config.useBack) i_return.style.display = '';
        if(config.useMore) i_right.style.display = '';
        if(config.moreCss) i_right.className = 'pull-right fa fa-1x5 ' + config.moreCss;
        if(config.backCall){
            jxhl.utility.attachClickEvent(i_return, config.backCall);
        }
        if(config.moreCall){
            jxhl.utility.attachClickEvent(i_right, config.moreCall);
        }
        ]]>
    </runnable>
</jxhl>
